### ISSUE TITLE
Team-99 code reivew

### ISSUE THREAD

**Issue by JelilFaisalAbudu** [Bluette1/tic-tac-toe#2]
- Nice work done. But what I'll suggest is that there should be a variable that is assigned the board's cells so that after the game has ended you can use it reset the board.

**Comment by descholar-ceo** [comment]
> * Nice work done. But what I'll suggest is that there should be a variable that is assigned the board's cells so that after the game has ended you can use it reset the board.

@JelilFaisalAbudu Thank you so much for this kind feedback, we really enjoy getting feedback so that we could improve our work to make it outstanding, we will implement your suggestion 100% on the current open Pull Request.

I am linking this Issue with the current open Pull Request since it will be fixed within that PR, so when the PR is merged, this issue will be closed automatically.
